textapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import listfunc ,Create ,detailfunc ,mypagefunc ,loginfunc  ,goodfunc ,profilefunc ,editmypagefunc ,deletefunc ,editdetailfunc ,chatfunc ,chatroomfunc ,aoyamafunc ,keiofunc ,profilefunc ,goodlistfunc ,homefunc ,logoutfunc,Login ,Logout, succeedfunc ,failfunc ,squeezefunc ,createfunc ,privacyfunc ,termsfunc
from . import views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView 

urlpatterns = [
    path('list/',listfunc,name='list'),
    path('create/',createfunc,name='create'),
    path('detail/<int:pk>',detailfunc,name='detail'),
    path('mypage/',mypagefunc,name='mypage'),
    path('login/',Login.as_view(),name='login'),
    path('logout/',Logout.as_view(),name='logout'),
    path('good/<int:pk>',goodfunc,name='good'),
    path('profile/',profilefunc,name='profile'),
    path('editmypage/',editmypagefunc,name='editmypage'),
    path('delete/<int:pk>',deletefunc,name='delete'),
    path('editdetail/<int:pk>', editdetailfunc,name='editdetail'),
    path('chatroom/<int:pk>',chatroomfunc,name='chatroom'),
    path('list/aoyama/',aoyamafunc,name='aoyama'),
    path('list/keio/' ,keiofunc,name='keio'),
    path('profile/<int:pk>',profilefunc,name='profile'),
    path('goodlist/',goodlistfunc,name="goodlist"),
    path('',homefunc,name='home'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('succeed/<int:pk>', succeedfunc, name='succeed'),
    path('fail/<int:pk>',failfunc,name="fail"),
    path('squeeze/',squeezefunc, name="squeeze"),
    path('privacy/',privacyfunc, name="privacy"),
    path('terms/',termsfunc, name="terms"),
    path('ads.txt', TemplateView.as_view(template_name='textapp/ads.txt',content_type='text/plain')),
]

textbookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('textapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

textapp/forms.py
from django import forms
from . import models
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm
)

User=get_user_model()

COLLEGE_CHOICES = (
    ('慶應義塾大学','慶應義塾大学'),
    ('早稲田大学','早稲田大学'),
    ('青山学院大学','青山学院大学'))

GENDER_CHOICES = (
    ('男性','男性'),
    ('女性','女性'))

STATUS_CHOICES = (
    ('e','全て'),
    (False,'販売中のみ')
)

QUALITY_CHOICES = (
    ('','状態を選択'),
    ('きれい','きれい'),
    ('少し書き込みあり','少し書き込みあり'),
    ('かなり書き込みあり','かなり書き込みあり'),
    ('あまりきれいでない','あまりきれいでない')
    
)


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Commentmodel
        fields = ('text',)
    
    text = forms.CharField(
        widget=forms.Textarea(),
        required=False,
        max_length=30,
        initial=''
    )

class UserForm(forms.Form):
    class Meta:
        model = models.Usermodel
        fields = ('username','college','gender','intro')
    
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder':'ユーザー名を入力（変更不可）'}
        ),
        required=True,
        max_length=20,
    )
    college = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder':'大学名、学部学科を入力'}
        ),
        #choices=COLLEGE_CHOICES,
        required=True,
        max_length=20,
    )
    intro = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={'placeholder':'自己紹介文を入力'}
        ),
        max_length=1000
    )
    gender = forms.ChoiceField(
        widget=forms.Select,
        choices=GENDER_CHOICES
    )

class UserForm2(forms.Form):
    class Meta:
        model = models.Usermodel
        fields = ('college','intro')
    college = forms.CharField(
        widget=forms.TextInput(),
        #choices=COLLEGE_CHOICES,
        required=True,
        max_length=20,
    )
    intro = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={'placeholder':'自己紹介文を入力'}
        ),
        max_length=1000
    )

class DetailForm(forms.Form):
    class Meta:
        model = models.Textbookmodel
        fields = ('title','content','images','collegecategory','status','price','campus',)

    images = forms.ImageField(
        required=True,
    )

    title = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={'placeholder':'例　経済学入門'}
        ),
        max_length=30,
    )
    content = forms.CharField(
        max_length=200,
        required=True,
        widget=forms.Textarea(
            attrs={'placeholder':'例　経済学部の必修科目の教科書です。定価5000円です。テストに出そうな部分も書き込んであります。よろしくお願いします。'}
        )
    )
    collegecategory = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(),
    )
    status = forms.ChoiceField(
        widget=forms.Select,
        choices=QUALITY_CHOICES,
    )
    price = forms.IntegerField(
        required=True,
        widget=forms.NumberInput(
            attrs={'placeholder':'例　2000'}
        )
    )
    campus = forms.CharField(
        max_length=30,
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder':'例　渋谷キャンパス'}
        )
    )

    
class ChatForm(forms.ModelForm):
    class Meta:
        model = models.Chatmodel
        fields = ('text',)
    text = forms.CharField(
        initial='',
        max_length=32,
        required = True,
        widget = forms.Textarea(
            attrs={'placeholder':'メッセージを入力'}
        )
    )

class SearchForm(forms.Form):
    search = forms.CharField(
        initial='',
        label='search',
        required = False, # 必須ではない
        widget=forms.TextInput(
        attrs={'placeholder':'キーワードを入力'}
    ))

class SqueezeForm(forms.Form):
    title = forms.CharField(
        initial='',
        label='title',
        required = False,
        widget=forms.TextInput(
            attrs={'placeholder':'タイトルを入力'}
        )
    )
    college = forms.CharField(
        initial='',
        label='college',
        required = False,
        widget = forms.TextInput(
            attrs={'placeholder':'大学名等を入力'}
        )
    )
    price = forms.IntegerField(
        initial='',
        label='price',
        required = False,
        widget=forms.NumberInput(
            attrs={'placeholder':'数字のみ　～円以下'}
        )

    ) 
    sellstatus = forms.ChoiceField(
        label='sellstatus',
        widget = forms.Select,
        choices = STATUS_CHOICES
    )



class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   {% block customcss%}
  <style>
    div.todo {
    position: relative;
    z-index: 1; /* 必要であればリンク要素の重なりのベース順序指定 */
    }
    div.todo a {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    text-indent:-999px;
    z-index: 2; /* 必要であればリンク要素の重なりのベース順序指定 */
}
  </style>
   {% endblock customcss%}

   {% block customscript %}
   
   {% endblock customscript %}


    <title></title>
    <meta name="viewport" content="width=device-width">
    <script type="text/javascript">
      function rset(f){
      f.submit();
      f.reset();
      }
      </script>
      <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-159027393-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-159027393-1');
</script>
<script data-ad-client="ca-pub-8034957177909576" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  </head>
  <body>
    
{% if messages %}
	<ul class="messages_ul" style="list-style: none;">
    {% for message in messages %}
    <div class ='todo'>
    <a href="{% url 'mypage' %}">
      <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ message }}</li>
      </a>
      </div>
		{% endfor %}
	</ul>
{% endif %}


    {% block header %}
    {% endblock header %}
    {% block content %}
    {% endblock content %}
    {% block footer %}
    {% endblock footer %}
    <address>
      <div class='footer'>
        <a href="{% url 'terms' %}">利用規約</a>　｜　<a href="{% url 'privacy' %}">プライバシーポリシー</a>
      </div>
      
      Copy Right TexTrade
        since 2020
    </address>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/chatroom.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<link rel='stylesheet' type='text/css' href="{% static 'chatroom-style.css' %}">
{% endblock customcss %}
{% block header %}
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'list' %}" style="font-size: 50px; font-family:fantasy;">TexTrade</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            
          {% if boolean == True %}
          <a class="nav-link" href="{% url 'mypage' %}">マイページ <span class="sr-only">(current)</span></a>
          {% else %}
          <a class="nav-link" href="{% url 'editmypage' %}">マイページ <span class="sr-only">(current)</span></a>
          {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'goodlist' %}">いいねリスト</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              大学カテゴリ
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'aoyama' %}">青山学院大学</a>
              <a class="dropdown-item" href="{% url 'keio' %}">慶應義塾大学</a>
              <a class="dropdown-item" href="#">早稲田大学</a>
              <a class="dropdown-item" href="#">and so on</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Another action</a>
          </li> -->
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
<div class="alert alert-info"  role="alert"> 
    <h4>{{ object_list.title }}の取引画面</h4>
  </div>
{% endblock header %}
{% block content %}
<div class='box'>
 <p>一対一のチャットボックスです。<br>日時や場所を決めるためにメッセージを送りましょう。</p>
  <div class='chatbox'>
    {% for message in chats%}
    <div class="msg">
    {% if message.sender == profile.username %}
    <div class="message">{{ message.text }} </div><br>
    <div class="date"><p>{{ message.created_date }}</p></div>
    {% endif %}
    {% if message.sender != profile.username %}
    <div class="messageif">{{ message.text }}</div><br>
    <div class="dateif"><p>{{ message.created_date }}</p></div>
    {% endif %}
    </div>
    {% endfor %}
</div>
    <div class='messagebox'>
    <form action='' method='POSt' enctype='multipart/form-data' value=''>
      {% csrf_token %}
        <h6>
        {{form.text}}
        <input type="button" value='送信' onclick="rset(this.form)"></h6>
    </form>
    </div>

<div class='content'>
  <h2>{{ object_list.title }}</h2>
<div class="image">{% if object_list.images %}
<p><img src="{{object_list.images.url}}" width=100% height=300  alt="..."></p>
{% endif %}</div>
<table border="1" width="100%" cellspacing="0" cellpadding="5" bordercolor="#333333" align="center">
<tr>
<td bgcolor="87cefa" valign="top" width="100px" align="center"><p>出品者</p></td>
<td><a href="{% url 'profile' object_list.pk %}" title="{{ object_list.author }}">{{ object_list.author }}</a></td></tr>
<tr>
<td bgcolor="87cefa" align="center"><p>内容</p></td>
<td><p>{{ object_list.content }}</p></td></tr>
<tr>
<td bgcolor="87cefa" align="center"><p>大学</p></td>
<td ><p>{{ object_list.collegecategory }}</p></td></tr>
<tr>
  <td bgcolor="87cefa" align="center"><p>キャンパス</p></td>
  <td ><p>{{ object_list.campus }}</p></td></tr>
<tr>
  <td bgcolor="87cefa" align="center"><p>状態</p></td>
  <td><p>{{ object_list.status }}</p></td></tr>
  <tr>
    <td bgcolor="87cefa" align="center"><p>値段</p></td>
    <td><p>￥{{ object_list.price }}</p></td></tr>
</table>
</div>

    <a href="{% url 'succeed' object_list.pk %}" class="btn btn-success btn-lg active" role="button" aria-pressed="true">取引完了</a>
    <a href="{% url 'fail' object_list.pk %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">取引を取り消す</a>
</div>

{% endblock content %}
{% block footer %}
{% endblock footer %}

templates/editdetail.html
{% extends 'base.html' %}
{% block customcss %}
<style>
  #id_title, #id_collegecategory, #id_campus{
    position:relative;
    width:250px;
    height:35px;
    border:solid;
    border-width: 0.5px;
    left:5px
  }
  #id_content{
    position:relative;
    width:300px;
    height:180px;
    border:solid;
    border-width:0.5px;
    left:5px;
  }
  #id_images, #id_status{
    position:relative;
    left:5px;
  }
  #id_price{
    position:relative;
    width:180px;
    height:35px;
    border:solid;
    border-width:0.5px;
    left:5px;
  }
  div.text{
    position:relative;
    left:5px;
    top:10px;
  }
  address{background-color: lightskyblue;
    color: #FFFFFF;
    text-align: center;
    position: relative;
    bottom:0px;
    width:100% ;
  }
  address a{
     color:#FFFEFF
  }
  div.box{
    width:100%;
   margin:auto;
   background-color:#FFFFFF;
   position: relative;
   padding-right:0px;
   padding-bottom:100px;
   min-height: 100vh;
   box-sizing: border-box;}
</style>
{% endblock customcss %}
{% block header %}
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'list' %}" style="font-size: 50px; font-family:fantasy;">TexTrade</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            
          {% if boolean == True %}
          <a class="nav-link" href="{% url 'mypage' %}">マイページ <span class="sr-only">(current)</span></a>
          {% else %}
          <a class="nav-link" href="{% url 'editmypage' %}">マイページ <span class="sr-only">(current)</span></a>
          {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'goodlist' %}">いいねリスト</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              大学カテゴリ
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'aoyama' %}">青山学院大学</a>
              <a class="dropdown-item" href="{% url 'keio' %}">慶應義塾大学</a>
              <a class="dropdown-item" href="#">早稲田大学</a>
              <a class="dropdown-item" href="#">and so on</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Another action</a>
          </li> -->
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
<div class="alert alert-info"  role="alert"> 
    <h3>出品の編集</h3>
  </div>
{% endblock header %}
{% block content %}
<div class="box">
<form action='' method='POST' enctype='multipart/form-data'>{% csrf_token %}
    
    
      <div class='text'><p>タイトル</p></div>
        <p>{{form.title}}</p>
        
    <div class='text'><p>内容</p></div>
        <p>{{ form.content }}</p>
        
      <div class='text'><p>画像</p></div>
        <p>
            {{form.images}}
        </p>
        
      <div class='text'><p>大学</p></div>
      <p>{{form.collegecategory}}
      </p>
      
    <div class='text'><p>キャンパス</p></div>
    <p>
        {{form.campus}}
    </p>
    
  <div class='text'><p>状態</p></div>
  <p>
      {{form.status}}
  </p>
  
  <div class='text'><p>値段</p></div>
  <p>
      {{form.price}}
  </p>

    <input type='hidden' name='user' value='{{user.username}}'>
    <input type='submit' value='保存する'/>
    <input type="button" value='取り消し' onclick="history.back()"/>
    </form>
    {% if post%}
    <a href="{% url 'delete' detail.pk %}">投稿を削除</a>
    {% endif %}
    </div>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- editdetail -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8034957177909576"
     data-ad-slot="6156470113"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
{% endblock content %}
{% block footer %}

{% endblock footer %}

templates/editmypage.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<style>
#id_college,#id_username{
    position:relative;
    width:250px;
    height:35px;
    border:solid;
    border-width: 0.5px;
    left:5px
  }
  #id_intro{
    position:relative;
    width:300px;
    height:180px;
    border:solid;
    border-width:0.5px;
    left:5px;
  }
  div.text{
    position:relative;
    left:5px;
    top:10px;
  }
  address{background-color: lightskyblue;
    color: #FFFFFF;
    text-align: center;
    position: relative;
    bottom:0px;
    width:100% ;
  }
  address a{
     color:#FFFEFF
  }
  div.box{
    width:100%;
   margin:auto;
   background-color:#FFFFFF;
   position: relative;
   padding-right:0px;
   padding-bottom:100px;
   min-height: 100vh;
   box-sizing: border-box;}
</style>
{% endblock customcss %}
{% block header %}
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'list' %}" style="font-size: 50px; font-family:fantasy;">TexTrade</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            
          {% if boolean == True %}
          <a class="nav-link" href="{% url 'mypage' %}">マイページ <span class="sr-only">(current)</span></a>
          {% else %}
          <a class="nav-link" href="{% url 'editmypage' %}">マイページ <span class="sr-only">(current)</span></a>
          {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'goodlist' %}">いいねリスト</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              大学カテゴリ
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'aoyama' %}">青山学院大学</a>
              <a class="dropdown-item" href="{% url 'keio' %}">慶應義塾大学</a>
              <a class="dropdown-item" href="#">早稲田大学</a>
              <a class="dropdown-item" href="#">and so on</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Another action</a>
          </li> -->
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
<div class="alert alert-info"  role="alert"> 
    <h3>マイページ</h3>
  </div>
{% endblock header %}
{% block content %}
<div class="box">
<p>ユーザーネームと性別は一度設定すると変更できません。大学名は学部等まで記入していただきますと、検索結果に反映されやすくなります。</p>
<form action='' method='POST' enctype='multipart/form-data'>{% csrf_token %}
  {% if error %}
  {{ error }}
  {% endif %}
  {% if boolean == True %}
  <div class='text'><p>大学</p></div>
        <p>{{form.college}}</p>
        
    <div class='text'><p>自己紹介</p></div>
        <p>{{ form.intro }}</p>
        
{% else %}
    <div class='text'><p>ユーザーネーム</p></div>
        <p>{{form.username}}</p>
        
    <div class='text'><p>性別</p></div>
        <p>{{ form.gender }}</p>
    <div class='text'><p>大学</p></div>
        <p>{{form.college}}</p>
        
    <div class='text'><p>自己紹介</p></div>
        <p>{{ form.intro }}</p>

    {% endif %}
    <input type='hidden' name='user' value='{{user.username}}'>
    <input type='submit' value='保存する'/>
    <input type="reset" value='取り消し'/>
    
    </form>
</div>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- editmypage -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8034957177909576"
     data-ad-slot="9954801240"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
{% endblock content %}
{% block footer %}

{% endblock footer %}

templates/login.html
{% extends 'base.html' %}
{% block header %}
{% endblock header %}
{% block content %}
<form class="form-signin" method='POST' action=''>{% csrf_token %}
    <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">ログイン</h1>
    <label for="inputText" class="sr-only">email</label>
    <input type="email" id="inputText" class="form-control" name='email' placeholder="メールアドレス" required autofocus>
    <label for="inputPassword" class="sr-only">password</label>
    <input type="password" id="inputPassword" class="form-control" name='password' placeholder="パスワード" required>
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> 次回ログインの時に自動で入力する
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">ログイン</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
  </form>
{% endblock content %}
{% block footer %}
{% endblock footer %}